### ISSUE TITLE
Problems with openssl support

### ISSUE THREAD

**Issue by rdravi110** [nov/rack-oauth2#90]
I am trying to build rack-oauth2 for Debian and I am getting the following error. 

```
Failures:

  1) Rack::OAuth2::Client#access_token! *args handling client authentication method when jwt_bearer auth method specified when private_key is given when EC key should be JWT bearer client assertion w/ auto-generated ES256-signed JWT assertion
     Failure/Error: private_key: OpenSSL::PKey::EC.new('prime256v1').generate_key,
     
     OpenSSL::PKey::PKeyError:
       pkeys are immutable on OpenSSL 3.0
     # ./spec/rack/oauth2/client_spec.rb:191:in `generate_key!'
     # ./spec/rack/oauth2/client_spec.rb:191:in `block (8 levels) in <top (required)>'
     # ./spec/rack/oauth2/client_spec.rb:89:in `block (5 levels) in <top (required)>'

Finished in 0.73756 seconds (files took 1.19 seconds to load)
403 examples, 1 failure

Failed examples:

rspec ./spec/rack/oauth2/client_spec.rb:197 # Rack::OAuth2::Client#access_token! *args handling client authentication method when jwt_bearer auth method specified when private_key is given when EC key should be JWT bearer client assertion w/ auto-generated ES256-signed JWT assertion  
```

Please help in resolving.

**Comment by nov** [comment]
this should fix it.
https://github.com/nov/rack-oauth2/commit/2803e1ba3c6a2946bf499255ca668127a27e6b3e

**Comment by rdravi110** [comment]
Thanks @nov , the commit did solve the issue.
