### ISSUE TITLE
rack-oauth2 and webmock don't expect the same HTTP response body type

### ISSUE THREAD

**Issue by freesteph** [nov/rack-oauth2#96]
rack-oauth2 expects a response to be [a hash and calls with_indifferent_access on it](https://github.com/nov/rack-oauth2/blob/master/lib/rack/oauth2/client.rb#L216), but webmock [doesn’t allow a hash for a response](https://github.com/bblimke/webmock/blob/master/lib/webmock/response.rb#L118-L123).

With a hash to agree with rack-oauth2, webmock complains:

```
Failures:

  1) Api doesn't agree on the return type
     Failure/Error:
       stub_request(:post, 'http://token-server.com/')
         .with(
           body: { 'grant_type' => 'client_credentials' },
           headers: {
             'Accept' => '*/*',
             'Accept-Encoding' => 'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
             'Authorization' => 'Basic bXkraWRlbnRpZmllcjpteStzZWNyZXQ=',
             'Content-Type' => 'application/x-www-form-urlencoded',
             'User-Agent' => 'Rack::OAuth2 (2.2.0)'
           }
     
     WebMock::Response::InvalidBody:
       must be one of: [Proc, IO, Pathname, String, Array]. 'Hash' given
     # ./spec.rb:19:in `block (2 levels) in <top (required)>'

Finished in 0.01229 seconds (files took 0.30281 seconds to load)
1 example, 1 failure
```

otherwise, to agree with Webmock and use a string:

```
Failures:

  1) Api doesn't agree on the return type
     Failure/Error: expect(subject.fetch!).to be_nil
     
     NoMethodError:
       undefined method `with_indifferent_access' for "{\"access_token\":\"token\"}":String
     
               token_hash = response.body.with_indifferent_access
                                         ^^^^^^^^^^^^^^^^^^^^^^^^
     # ./main.rb:8:in `fetch!'
     # ./spec.rb:23:in `block (2 levels) in <top (required)>'

Finished in 0.01771 seconds (files took 0.2967 seconds to load)
1 example, 1 failure
```
I've made a repo for you to check out the bug: https://github.com/freesteph/rack-oauth2-webmock-issue

**Comment by nov** [comment]
return json content, then faraday handle it as hash

**Comment by freesteph** [comment]
Hi @nov, thanks for your quick answer. I'm returning `JSON.generate({ key: val })` isn't that JSON content?

**Comment by nov** [comment]
if it's `content-type: plain/text`, then no.
